// <auto-generated />
namespace Resume.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class preCvToActivity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(preCvToActivity));
        
        string IMigrationMetadata.Id
        {
            get { return "201308070900574_preCvToActivity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
